### ISSUE TITLE
Bug: cannot use pycrypto with python3.11

### ISSUE THREAD

**Issue by mims92** [aws/aws-sam-build-images#105]
### Description:
When trying to build/test an 3.11 Python application that requires pycrypto, there is this issue:
````
[...]
    gcc -pthread -Wsign-compare -fwrapv -Wall -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/ -I/var/lang/include/python3.11 -c src/_fastmath.c -o build/temp.linux-x
86_64-cpython-311/src/_fastmath.o
      In file included from /var/lang/include/python3.11/Python.h:12:0,
                       from src/_fastmath.c:31:
      /var/lang/include/python3.11/pyconfig.h:1784:0: warning: "_POSIX_C_SOURCE" redefined
       #define _POSIX_C_SOURCE 200809L
     
      In file included from /usr/include/bits/libc-header-start.h:33:0,
                       from /usr/include/stdio.h:27,
                       from src/_fastmath.c:29:
      /usr/include/features.h:289:0: note: this is the location of the previous definition
       # define _POSIX_C_SOURCE 199506L
     
      src/_fastmath.c:33:10: fatal error: longintrepr.h: No such file or directory
       #include <longintrepr.h>    /* for conversions */
                ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
````

The issue doesn't occur with Python3.9 image.

### Steps to reproduce:
1. Create an application with SAM using Python3.11 runtime
2. add `pycrypto` in the `requirements.txt` file
3. Build the application

### Observed result:
```
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

```

### Expected result:
The application build correctly.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Docker
4. If using SAM CLI, `sam --version`: 23.1.2
5. AWS region: /

**Comment by mndeveci** [comment]
Hi there,

It looks like it is trying to compile the c bindings and it is failing with new python3.11 image. It is probably caused by gcc version (or other libraries related to gcc). Some python libraries provide their compiled c bindings but for this one, it needs to be compiled from scratch.

When I search for the library it seems that it is not been maintained anymore, so I assume it is not updating its source code for newer tools https://www.pycrypto.org/

You can create your own image which will contain a combination of the python version you need and the other tooling that this library requires. And then you can provide the custom image during build with `--build-image` option. Or, you can also create and Image based Lambda function which then can be build from different base images.

**Comment by hnnasit** [comment]
Closing this issue since it's been inactive for a while now. Feel free to create a new issue if you have any questions or concerns.
